/****** Object:  Index [IX_CO_PROCESSHISTORY_COMPONENTID]    Script Date: 12/9/2014 11:45:19 AM ******/
DROP INDEX [IX_CO_PROCESSHISTORY_COMPONENTID] ON [CADIS_SYS].[CO_PROCESSHISTORY]
GO

/****** Object:  Index [IX_CO_PROCESSHISTORY_COMPONENTID]    Script Date: 12/9/2014 11:45:19 AM ******/
CREATE NONCLUSTERED INDEX [IX_CO_PROCESSHISTORY_COMPONENTID] ON [CADIS_SYS].[CO_PROCESSHISTORY]
(
	[COMPONENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


