/****** Object:  Index [IX_CO_PROCESSLOG_RUNID]    Script Date: 12/9/2014 11:44:33 AM ******/
DROP INDEX [IX_CO_PROCESSLOG_RUNID] ON [CADIS_SYS].[CO_PROCESSLOG]
GO

/****** Object:  Index [IX_CO_PROCESSLOG_RUNID]    Script Date: 12/9/2014 11:44:33 AM ******/
CREATE NONCLUSTERED INDEX [IX_CO_PROCESSLOG_RUNID] ON [CADIS_SYS].[CO_PROCESSLOG]
(
	[RUNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


