/****** Object:  Index [IX_CO_PROCESSHISTORY_TOPLEVELRUNID]    Script Date: 12/9/2014 11:48:03 AM ******/
DROP INDEX [IX_CO_PROCESSHISTORY_TOPLEVELRUNID] ON [CADIS_SYS].[CO_PROCESSHISTORY]
GO

/****** Object:  Index [IX_CO_PROCESSHISTORY_TOPLEVELRUNID]    Script Date: 12/9/2014 11:48:03 AM ******/
CREATE NONCLUSTERED INDEX [IX_CO_PROCESSHISTORY_TOPLEVELRUNID] ON [CADIS_SYS].[CO_PROCESSHISTORY]
(
	[TOPLEVELRUNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


